from .customWords import customWords
from .ARAM.mainAram import mainAram
from .COMPO.compos import compos
from .clash import clash
from .help import help
from .music import music
from .snifsnouf import snifsnouf
from .jvaisVX import jvaisVX
from .calculs import calculs
from .fights import fights
from .recherche import recherche