from .bolosse import bolosse
from .combat import combat
from .customWords import customW
from .ARAM import mainAram
from .COMPO import compos
from .jvaisVX import main
from .random_number import random_number
from .clash import clash
from .youtube_search import youtube_search
from .justeprix import justeprix
from .duel import duel
from .help import help
from .music import music