from .customWords import customWords
from .ARAM.mainAram import mainAram
from .COMPO.compos import compos
from .snifsnouf import snifsnouf
from .recherche import recherche
from .jvaisVX import jvaisVX
from .calculs import calculs
from .fights import fights
from .music import music
from .clash import clash
from .help import help
#from .jumbledWordsRes.jumbledWordsResolver import jumbledWordsResolver
from .ytbAlert import check_new_video
from .calendrier import calendrier